'use strict';
const $=(s,e=document)=>e.querySelector(s),$$=(s,e=document)=>[...e.querySelectorAll(s)];
const APP='HANE_PREMIUM_V2_DATA',META='HANE_PREMIUM_V2_META',enc=new TextEncoder(),dec=new TextDecoder();
let state=null,key=null,current='home',modal=null,pinBuf='',lockTimer=null,hiddenAt=null,reportPeriod='month',setupPhotoData='';
const CATS=['Kira','Aidat','Market','Faturalar','Elektrik','Su','Doğalgaz','İnternet','Cep Telefonu','Ulaşım','Sağlık','Eğlence','Diğer'];
const ICON={Kira:'⌂',Aidat:'▦',Market:'🛒',Faturalar:'▣',Elektrik:'⚡',Su:'💧',Doğalgaz:'🔥',İnternet:'◉','Cep Telefonu':'▯',Ulaşım:'◆',Sağlık:'✚',Eğlence:'♪',Diğer:'●'};
const QUOTES=['Bugün küçük bir adım, yarın büyük bir değişimdir.','Disiplin, özgürlüğün kapısını açar.','Paranı yönetmek, geleceğine yön vermektir.','Küçük birikimler büyük rahatlıklar getirir.','Planı olan para, kaybolmaz.','Bugünün düzeni yarının huzurudur.'];
const now=new Date();
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function ym(d=new Date()){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')}
function iso(d=new Date()){return d.toISOString().slice(0,10)}
function money(n){return new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY',maximumFractionDigits:0}).format(Number(n||0))}
function mname(m){let [y,x]=m.split('-').map(Number);return new Date(y,x-1,1).toLocaleDateString('tr-TR',{month:'long',year:'numeric'})}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(t){let x=document.createElement('div');x.className='toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),2200)}
function defaultState(){let m=ym();return{version:1,selectedMonth:m,profile:{name:'Mehmet',photo:'',motto:'Disiplin, özgürlüğün kapısını açar.'},settings:{lockMinutes:15,leadDays:3,notifications:false},incomes:[{id:uid(),title:'Maaş (Emekli)',amount:25000,date:m+'-20',recurring:true,day:20}],expenses:[['Kira',12000,1,'Kira'],['Aidat',750,5,'Aidat'],['İnternet',350,10,'İnternet'],['Elektrik',870,12,'Elektrik'],['Su',320,15,'Su'],['Doğalgaz',1250,18,'Doğalgaz'],['Cep Telefonu',450,20,'Cep Telefonu']].map(([title,amount,day,category])=>({id:uid(),title,amount,date:m+'-'+String(day).padStart(2,'0'),dueDate:m+'-'+String(day).padStart(2,'0'),recurring:true,day,category,paid:false})),cards:[{id:uid(),bank:'Yapı Kredi',name:'World',last4:'1234',limit:100000,balance:8450,statementDay:10,dueDay:22,style:'goldish',network:'VISA',transactions:[]},{id:uid(),bank:'Garanti BBVA',name:'Bonus',last4:'5678',limit:75000,balance:2120,statementDay:15,dueDay:27,style:'blueish',network:'VISA',transactions:[]}]}}
function b64(a){let s='';for(const b of new Uint8Array(a))s+=String.fromCharCode(b);return btoa(s)}function ub64(s){let r=atob(s),a=new Uint8Array(r.length);for(let i=0;i<r.length;i++)a[i]=r.charCodeAt(i);return a}
async function derive(pin,salt){let m=await crypto.subtle.importKey('raw',enc.encode('HANE|'+pin),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},m,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function encrypt(st,k){let iv=crypto.getRandomValues(new Uint8Array(12)),data=await crypto.subtle.encrypt({name:'AES-GCM',iv},k,enc.encode(JSON.stringify(st)));return{iv:b64(iv),data:b64(data)}}
async function decrypt(box,k){let p=await crypto.subtle.decrypt({name:'AES-GCM',iv:ub64(box.iv)},k,ub64(box.data));return JSON.parse(dec.decode(p))}
function meta(){try{return JSON.parse(localStorage.getItem(META)||'null')}catch{return null}}
async function save(){
  if(!state||!key)return;
  try{localStorage.setItem(APP,JSON.stringify(await encrypt(state,key)))}
  catch(e){throw new Error('Depolama dolu. Büyük fiş/profil fotoğraflarını azaltın veya yedek alıp eski fotoğrafları silin.')}
}
async function setup(pin,st){
  let salt=crypto.getRandomValues(new Uint8Array(16));
  const newKey=await derive(pin,salt);
  const box=await encrypt(st,newKey);
  try{
    localStorage.setItem(APP,JSON.stringify(box));
    localStorage.setItem(META,JSON.stringify({salt:b64(salt),publicName:st.profile.name,publicPhoto:st.profile.photo||''}));
  }catch(e){
    localStorage.removeItem(APP);localStorage.removeItem(META);
    throw new Error('Cihaz depolamasına veri yazılamadı. Profil fotoğrafını küçültüp tekrar deneyin.');
  }
  key=newKey;state=st;
}
async function unlock(pin){try{let m=meta();key=await derive(pin,ub64(m.salt));state=await decrypt(JSON.parse(localStorage.getItem(APP)),key);return true}catch{return false}}
function totals(m=state.selectedMonth){let inc=state.incomes.filter(x=>x.date.startsWith(m)).reduce((s,x)=>s+Number(x.amount),0),exp=state.expenses.filter(x=>x.date.startsWith(m)).reduce((s,x)=>s+Number(x.amount),0);return{inc,exp,rem:inc-exp}}
function recur(m){let [y,mo]=m.split('-').map(Number),last=new Date(y,mo,0).getDate(),changed=false;for(const src of [...state.incomes])if(src.recurring&&!src.date.startsWith(m)&&!state.incomes.some(x=>x.source===src.id&&x.date.startsWith(m))){let d=String(Math.min(src.day||1,last)).padStart(2,'0');state.incomes.push({...src,id:uid(),source:src.id,date:m+'-'+d});changed=true}for(const src of [...state.expenses])if(src.recurring&&!src.date.startsWith(m)&&!state.expenses.some(x=>x.source===src.id&&x.date.startsWith(m))){let d=String(Math.min(src.day||1,last)).padStart(2,'0');state.expenses.push({...src,id:uid(),source:src.id,date:m+'-'+d,dueDate:m+'-'+d,paid:false});changed=true}if(changed)save()}
function nextDue(day){let t=new Date(),d=new Date(t.getFullYear(),t.getMonth(),+day);d.setHours(0,0,0,0);let td=new Date(t.getFullYear(),t.getMonth(),t.getDate());if(d<td)d=new Date(t.getFullYear(),t.getMonth()+1,+day);return d}
function recCard(){let t=new Date(),best=null;for(const c of state.cards){let pay=t.getDate()>+c.statementDay?new Date(t.getFullYear(),t.getMonth()+1,+c.dueDay):new Date(t.getFullYear(),t.getMonth(),+c.dueDay);if(pay<t)pay=new Date(t.getFullYear(),t.getMonth()+1,+c.dueDay);let days=Math.ceil((pay-t)/86400000),util=(+c.balance/Math.max(1,+c.limit))*100,score=days-(util>80?20:util>60?8:0);if(!best||score>best.score)best={...c,days,score}}return best}
function dues(){let lead=+state.settings.leadDays||3,t=new Date(),a=[];t.setHours(0,0,0,0);state.expenses.filter(x=>!x.paid).forEach(x=>{let d=new Date(x.dueDate+'T00:00:00'),days=Math.ceil((d-t)/86400000);if(days<=lead)a.push({type:'expense',id:x.id,title:x.title,amount:x.amount,days})});state.cards.forEach(c=>{let d=nextDue(c.dueDay),days=Math.ceil((d-t)/86400000);if(+c.balance>0&&days<=lead)a.push({type:'card',id:c.id,title:c.bank+' '+c.name,amount:c.balance,days})});return a.sort((a,b)=>a.days-b.days)}
function profileImg(){return state.profile.photo?`<img src="${state.profile.photo}" style="width:100%;height:100%;object-fit:cover">`:esc(state.profile.name?.[0]||'H')}
function buildTopBar(){if(current==='home')return`<div class="topbar"><div class="avatar">${profileImg()}</div><div class="brand">HANE</div><button class="iconbtn" data-tab="alerts">🔔</button></div>`;let names={transactions:'İşlemler',cards:'Kredi Kartlarım',reports:'Raporlar',profile:'Profilim',alerts:'Bildirimler',chart:'Detaylı Grafik',fixed:'Sabit Giderler'};return`<div class="topbar"><button class="backbtn" data-action="back">‹</button><div class="page-title">${names[current]||'HANE'}</div><div style="width:38px"></div></div>`}
function nav(){let a=[['home','⌂','Ana Sayfa'],['transactions','▤','İşlemler'],['cards','▭','Kartlar'],['reports','▥','Raporlar'],['profile','●','Profil']];return`<nav class="nav">${a.map(i=>`<button data-tab="${i[0]}" class="${current===i[0]?'active':''}"><span>${i[1]}</span><span>${i[2]}</span></button>`).join('')}</nav>`}
function render(){recur(state.selectedMonth);$('#app').innerHTML=`<main class="phone">${buildTopBar()}<div class="content">${view()}</div>${nav()}</main>${current!=='profile'?'<button class="fab" data-action="quick">+</button>':''}${modal?`<div class="modal"><div class="sheet"><div class="sheet-head"><b>${modal.title}</b><button class="close" data-action="close">×</button></div>${modal.body}</div></div>`:''}`;bind();if(current==='reports'||current==='chart')requestAnimationFrame(draw)}
function view(){return({home,transactions,cards,reports,profile,alerts,chart:reports,fixed:fixedPage}[current]||home)()}
function home(){let T=totals(),sum=Math.max(1,Math.max(0,T.inc)+Math.max(0,T.exp)+Math.max(0,T.rem)),p1=Math.max(0,T.inc)/sum*100,p2=p1+Math.max(0,T.exp)/sum*100,r=recCard(),q=QUOTES[Math.floor(Date.now()/86400000)%QUOTES.length];return`<div class="quote card gold-card"><div class="qicon">✦</div><div><b>Bugünün Sözü</b><span>“${q}”</span></div></div><div class="monthbar"><button data-action="prev">‹</button><b>${mname(state.selectedMonth)}</b><button data-action="next">›</button></div><div class="donut-row"><div class="donut" data-tab="chart" style="--p1:${p1}%;--p2:${p2}%"><div class="donut-center"><small>Kalan</small><strong>${money(T.rem)}</strong></div></div></div><div class="stats"><div class="stat"><div class="label"><i class="dot" style="background:var(--blue)"></i>Gelir</div><b class="blue">${money(T.inc)}</b></div><div class="stat"><div class="label"><i class="dot" style="background:var(--red)"></i>Gider</div><b class="red">${money(T.exp)}</b></div><div class="stat"><div class="label"><i class="dot" style="background:var(--green)"></i>Kalan</div><b class="green">${money(T.rem)}</b></div></div><div class="section-title"><b>Önerilen Kart</b><span class="link">Hesap kesimine göre</span></div>${r?`<div class="recommended card gold-card" data-action="editCard" data-id="${r.id}"><small>ÖNERİLEN KART</small><div class="card-name">${esc(r.bank)} ${esc(r.name)} •••• ${r.last4}</div><div class="chip"></div><div class="card-meta">Bu ay avantajlı · Ödemeye yaklaşık ${r.days} gün</div><div class="visa">${r.network}</div></div>`:'<div class="empty">Kart eklenmedi.</div>'}<div class="section-title"><b>Yaklaşan Ödemeler</b><span class="link" data-tab="alerts">Tümünü Gör ›</span></div><div class="list">${dues().slice(0,3).map(d=>dueRow(d)).join('')||'<div class="empty">Yaklaşan ödeme yok.</div>'}</div>`}
function dueRow(d){let e=state.expenses.find(x=>x.id===d.id);return`<div class="list-item" data-action="${d.type==='card'?'editCard':'editExpense'}" data-id="${d.id}"><div class="item-icon">${d.type==='card'?'▭':ICON[e?.category]||'₺'}</div><div class="item-main"><b>${esc(d.title)}</b><small>${d.days<0?Math.abs(d.days)+' gün gecikti':d.days===0?'Bugün':d.days+' gün kaldı'}</small></div><div class="item-side"><b class="${d.days<=0?'red':'gold'}">${money(d.amount)}</b></div></div>`}
function transactions(){let m=state.selectedMonth,a=[...state.incomes.filter(x=>x.date.startsWith(m)).map(x=>({...x,type:'income'})),...state.expenses.filter(x=>x.date.startsWith(m)).map(x=>({...x,type:'expense'}))].sort((a,b)=>b.date.localeCompare(a.date));return`<div class="segment"><button class="active" data-filter="all">Tümü</button><button data-filter="income">Gelir</button><button data-filter="expense">Gider</button></div><div class="monthbar"><button data-action="prev">‹</button><b>${mname(m)}</b><button data-action="next">›</button></div><div class="list" id="txlist">${a.map(txRow).join('')||'<div class="empty">Kayıt yok.</div>'}</div>`}
function txRow(x){return`<div class="list-item" data-type="${x.type}" data-action="${x.type==='income'?'editIncome':'editExpense'}" data-id="${x.id}"><div class="item-icon">${x.type==='income'?'₺':ICON[x.category]||'●'}</div><div class="item-main"><b>${esc(x.title)}</b><small>${esc(x.category||'Gelir')} · ${x.date}${x.recurring?' · Sabit':''}</small></div><div class="item-side"><b class="${x.type==='income'?'green':'red'}">${x.type==='income'?'+':'-'}${money(x.amount)}</b>${x.type==='expense'&&x.paid?'<small class="green">Ödendi</small>':''}</div></div>`}
function fixedPage(){return`<div class="section-title"><b>Sabit Giderler</b><button class="btn small" data-action="addExpense">+ Ekle</button></div><div class="list">${state.expenses.filter(x=>x.recurring).map(x=>txRow({...x,type:'expense'})).join('')}</div>`}
function cards(){return`<div class="section-title"><b>Kredi Kartlarım</b><button class="btn small" data-action="addCard">+ Kart Ekle</button></div>${state.cards.map(cardHTML).join('')||'<div class="empty">Kart yok.</div>'}`}
function cardHTML(c){return`<div class="credit-card card ${c.style}" data-action="editCard" data-id="${c.id}"><div>${esc(c.bank)}</div><div class="network">${c.network}</div><div class="card-name">${esc(c.name)}</div><div class="digits">•••• •••• •••• ${c.last4}</div><div class="grid"><div><small>Limit</small><b>${money(c.limit)}</b></div><div><small>Güncel Borç</small><b>${money(c.balance)}</b></div><div><small>Hesap Kesim</small><b>Her ayın ${c.statementDay}'u</b></div><div><small>Son Ödeme</small><b>Her ayın ${c.dueDay}'si</b></div></div><button class="btn goldbtn small" style="margin-top:14px;width:100%" data-action="cardSpend" data-id="${c.id}">Harcama Ekle / Gör</button></div>`}
function reports(){let T=totals();return`<div class="segment"><button data-period="day" class="${reportPeriod==='day'?'active':''}">Gün</button><button data-period="week" class="${reportPeriod==='week'?'active':''}">Hafta</button><button data-period="month" class="${reportPeriod==='month'?'active':''}">Ay</button><button data-period="year" class="${reportPeriod==='year'?'active':''}">Yıl</button></div><div class="monthbar"><button data-action="prev">‹</button><b>${mname(state.selectedMonth)}</b><button data-action="next">›</button></div><div class="stats"><div class="stat"><div class="label">Gelir</div><b class="blue">${money(T.inc)}</b></div><div class="stat"><div class="label">Gider</div><b class="red">${money(T.exp)}</b></div><div class="stat"><div class="label">Kalan</div><b class="green">${money(T.rem)}</b></div></div><div class="chartbox card"><canvas id="chart"></canvas><div class="legend"><span>🔵 Gelir</span><span>🔴 Gider</span><span>🟢 Kalan</span></div></div>${catAnalysis()}`}
function catAnalysis(){let xs=state.expenses.filter(x=>x.date.startsWith(state.selectedMonth)),s={};xs.forEach(x=>s[x.category]=(s[x.category]||0)+Number(x.amount));let max=Math.max(1,...Object.values(s)),tot=Object.values(s).reduce((a,b)=>a+b,0)||1;return`<div class="section-title"><b>Gider Dağılımı</b></div><div class="card" style="padding:14px">${Object.entries(s).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="category-row"><div><div style="display:flex;justify-content:space-between;font-size:12px;margin-bottom:5px"><span>${k}</span><b>${money(v)}</b></div><div class="bar"><i style="width:${v/max*100}%"></i></div></div><span>${Math.round(v/tot*100)}%</span></div>`).join('')||'<div class="empty">Veri yok.</div>'}</div>`}
function profile(){return`<div class="profile-card card gold-card"><div class="profile-big">${profileImg()}</div><h2>${esc(state.profile.name)}</h2><em>“${esc(state.profile.motto)}”</em></div><div class="card" style="padding:5px 14px;margin-top:12px"><div class="setting-item" data-action="editProfile"><span>●</span><span>Kişisel Bilgiler</span><b>›</b></div><div class="setting-item" data-action="fixed"><span>₺</span><span>Sabit Giderler</span><b>›</b></div><div class="setting-item" data-action="notify"><span>🔔</span><span>Bildirimler</span><div class="switch ${state.settings.notifications?'on':''}"><i></i></div></div><div class="setting-item" data-action="backup"><span>☁</span><span>Şifreli Yedek Oluştur</span><b>›</b></div><div class="setting-item" data-action="restore"><span>↻</span><span>Yedekten Geri Yükle</span><b>›</b></div><div class="setting-item" data-action="changePin"><span>⌁</span><span>PIN Değiştir</span><b>›</b></div><div class="setting-item" data-action="lock"><span>◉</span><span>Şimdi Kilitle</span><b>›</b></div></div><div class="notice" style="margin-top:12px">Veriler cihazında AES-256-GCM ile şifreli tutulur. Tam kart numarası, CVV ve banka parolası kaydedilmez.</div>`}
function alerts(){let a=dues();return`<div class="segment"><button class="active">Tümü</button><button>Ödemeler</button><button>Hatırlatmalar</button></div><div class="section-title"><b>Ödenmesi Gerekenler</b></div><div class="list">${a.map(dueRow).join('')||'<div class="empty">Bekleyen ödeme yok.</div>'}</div>`}
function inp(n,l,v='',t='text',ex=''){return`<div class="field"><label>${l}</label><input name="${n}" type="${t}" value="${esc(v)}" ${ex}></div>`}function sel(n,l,opts,v){return`<div class="field"><label>${l}</label><select name="${n}">${opts.map(o=>`<option ${o===v?'selected':''}>${o}</option>`).join('')}</select></div>`}
function expenseForm(x={}){return`<form class="form" id="expenseForm">${inp('title','Açıklama',x.title||'')}${inp('amount','Tutar',x.amount||'','number','step="0.01"')}${sel('category','Kategori',CATS,x.category||'Faturalar')}<div class="row2">${inp('date','Tarih',x.date||iso(),'date')}${inp('dueDate','Son Ödeme Tarihi',x.dueDate||x.date||iso(),'date')}</div><div class="row2">${inp('day','Tekrar Günü',x.day||1,'number','min="1" max="31"')}<div class="field"><label>Sabit Gider</label><select name="recurring"><option value="false" ${!x.recurring?'selected':''}>Hayır</option><option value="true" ${x.recurring?'selected':''}>Evet</option></select></div></div><div class="field"><label>Ödeme Durumu</label><select name="paid"><option value="false" ${!x.paid?'selected':''}>Ödenmedi</option><option value="true" ${x.paid?'selected':''}>Ödendi</option></select></div><button type="button" class="btn" data-action="photo">📷 Fiş / Fotoğraf Ekle</button>${x.attachment?'<span class="badge">Fotoğraf var</span>':''}<button class="btn goldbtn">Kaydet</button>${x.id?`<button type="button" class="btn redbtn" data-action="delExpense" data-id="${x.id}">Kaydı Sil</button>`:''}</form>`}
function incomeForm(x={}){return`<form class="form" id="incomeForm">${inp('title','Gelir Adı',x.title||'')}${inp('amount','Tutar',x.amount||'','number')}${inp('date','Tarih',x.date||iso(),'date')}<div class="row2">${inp('day','Tekrar Günü',x.day||20,'number')}<div class="field"><label>Sabit Gelir</label><select name="recurring"><option value="false" ${!x.recurring?'selected':''}>Hayır</option><option value="true" ${x.recurring?'selected':''}>Evet</option></select></div></div><button class="btn goldbtn">Kaydet</button>${x.id?`<button type="button" class="btn redbtn" data-action="delIncome" data-id="${x.id}">Kaydı Sil</button>`:''}</form>`}
function cardForm(c={}){return`<form class="form" id="cardForm">${inp('bank','Banka',c.bank||'')}${inp('name','Kart Adı',c.name||'')}${inp('last4','Son 4 Hane',c.last4||'','text','maxlength="4" inputmode="numeric"')}<div class="row2">${inp('limit','Limit',c.limit||'','number')}${inp('balance','Güncel Borç',c.balance||0,'number')}</div><div class="row2">${inp('statementDay','Hesap Kesim Günü',c.statementDay||10,'number')}${inp('dueDay','Son Ödeme Günü',c.dueDay||20,'number')}</div>${sel('style','Kart Rengi',['goldish','blueish','purpleish'],c.style||'goldish')}<button class="btn goldbtn">Kaydet</button>${c.id?`<button type="button" class="btn" data-action="cardSpend" data-id="${c.id}">Kart Harcamaları</button><button type="button" class="btn redbtn" data-action="delCard" data-id="${c.id}">Kartı Sil</button>`:''}</form>`}
function spendForm(c){return`<div class="notice">Kart harcaması otomatik olarak giderlere de eklenir.</div><form class="form" id="spendForm" style="margin-top:12px">${inp('amount','Tutar','','number')}${sel('category','Kategori',CATS,'Market')}${inp('title','Açıklama','')}${inp('date','Tarih',iso(),'date')}<div class="row2"><button type="button" class="btn" data-action="camera">📷 Kamera</button><button type="button" class="btn" data-action="gallery">🖼 Fotoğraf</button></div><button class="btn goldbtn">Harcamayı Kaydet</button></form><div class="section-title"><b>Geçmiş Harcamalar</b></div><div class="list">${(c.transactions||[]).slice().reverse().map(t=>`<div class="list-item" data-action="editTx" data-card="${c.id}" data-id="${t.id}"><div class="item-icon">${ICON[t.category]||'₺'}</div><div class="item-main"><b>${esc(t.title||t.category)}</b><small>${t.date}</small></div><div class="item-side"><b class="red">-${money(t.amount)}</b></div></div>`).join('')||'<div class="empty">Harcama yok.</div>'}</div>`}
function profileForm(){return`<form class="form" id="profileForm"><div class="photo-pick"><div class="avatar">${profileImg()}</div><button type="button" class="btn" data-action="profilePhoto">Profil Resmi Seç</button></div>${inp('name','İsim',state.profile.name)}<div class="field"><label>Motto</label><textarea name="motto">${esc(state.profile.motto)}</textarea></div><div class="row2">${inp('lockMinutes','Otomatik Kilit (dk)',state.settings.lockMinutes,'number')}${inp('leadDays','Uyarı (gün önce)',state.settings.leadDays,'number')}</div><button class="btn goldbtn">Kaydet</button></form>`}
function open(title,body,extra={}){modal={title,body,...extra};render()}function close(){modal=null;render()}function formData(f){return Object.fromEntries(new FormData(f).entries())}
function bind(){$$('[data-tab]').forEach(x=>x.onclick=()=>{current=x.dataset.tab;modal=null;render()});$$('[data-action]').forEach(x=>x.onclick=e=>{e.stopPropagation();act(x.dataset.action,x)});let f=$('#expenseForm');if(f)f.onsubmit=e=>{e.preventDefault();saveExpense(formData(f),modal.id)};f=$('#incomeForm');if(f)f.onsubmit=e=>{e.preventDefault();saveIncome(formData(f),modal.id)};f=$('#cardForm');if(f)f.onsubmit=e=>{e.preventDefault();saveCard(formData(f),modal.id)};f=$('#spendForm');if(f)f.onsubmit=e=>{e.preventDefault();saveSpend(formData(f),modal.cardId)};f=$('#profileForm');if(f)f.onsubmit=e=>{e.preventDefault();let d=formData(f);state.profile.name=d.name;state.profile.motto=d.motto;state.settings.lockMinutes=+d.lockMinutes||15;state.settings.leadDays=+d.leadDays||3;let mm=meta();mm.publicName=state.profile.name;mm.publicPhoto=state.profile.photo||'';localStorage.setItem(META,JSON.stringify(mm));save();close();toast('Profil güncellendi')};$$('[data-filter]').forEach(b=>b.onclick=()=>{$$('#txlist .list-item').forEach(r=>r.style.display=b.dataset.filter==='all'||r.dataset.type===b.dataset.filter?'grid':'none')});$$('[data-period]').forEach(b=>b.onclick=()=>{reportPeriod=b.dataset.period;render()});let et=$('#editTxForm');if(et)et.onsubmit=e=>{e.preventDefault();updateTx(formData(et),modal.cardId,modal.txId)}}
async function act(a,e){if(a==='back'){current='home';render()}else if(a==='prev'||a==='next'){let [y,m]=state.selectedMonth.split('-').map(Number),d=new Date(y,m-1,1);d.setMonth(d.getMonth()+(a==='next'?1:-1));state.selectedMonth=ym(d);await save();render()}else if(a==='quick')open('Yeni Kayıt','<div class="form"><button class="btn goldbtn" data-action="addExpense">Gider Ekle</button><button class="btn" data-action="addIncome">Gelir Ekle</button><button class="btn" data-action="addCard">Kredi Kartı Ekle</button></div>');else if(a==='close')close();else if(a==='addExpense')open('Gider Ekle',expenseForm());else if(a==='editExpense'){let x=state.expenses.find(x=>x.id===e.dataset.id);open('Gideri Düzenle',expenseForm(x),{id:x.id})}else if(a==='delExpense'){state.expenses=state.expenses.filter(x=>x.id!==e.dataset.id);await save();close();toast('Gider silindi')}else if(a==='addIncome')open('Gelir Ekle',incomeForm());else if(a==='editIncome'){let x=state.incomes.find(x=>x.id===e.dataset.id);open('Geliri Düzenle',incomeForm(x),{id:x.id})}else if(a==='delIncome'){state.incomes=state.incomes.filter(x=>x.id!==e.dataset.id);await save();close();toast('Gelir silindi')}else if(a==='addCard')open('Kart Ekle',cardForm());else if(a==='editCard'){let c=state.cards.find(x=>x.id===e.dataset.id);open('Kartı Düzenle',cardForm(c),{id:c.id})}else if(a==='delCard'){state.cards=state.cards.filter(x=>x.id!==e.dataset.id);await save();close();toast('Kart silindi')}else if(a==='cardSpend'){let c=state.cards.find(x=>x.id===e.dataset.id);open(c.bank+' '+c.name,spendForm(c),{cardId:c.id})}else if(a==='editTx'){let c=state.cards.find(x=>x.id===e.dataset.card),t=c.transactions.find(x=>x.id===e.dataset.id);open('Kart Harcamasını Düzenle',`<form class="form" id="editTxForm">${inp('amount','Tutar',t.amount,'number')}${sel('category','Kategori',CATS,t.category)}${inp('title','Açıklama',t.title)}${inp('date','Tarih',t.date,'date')}<button class="btn goldbtn">Kaydet</button><button type="button" class="btn redbtn" data-action="delTx" data-card="${c.id}" data-id="${t.id}">Sil</button></form>`,{cardId:c.id,txId:t.id})}else if(a==='delTx'){await deleteTx(e.dataset.card,e.dataset.id)}else if(a==='fixed'){current='fixed';render()}else if(a==='editProfile')open('Profili Düzenle',profileForm());else if(a==='profilePhoto')$('#profileInput').click();else if(a==='photo'||a==='gallery')$('#galleryInput').click();else if(a==='camera')$('#cameraInput').click();else if(a==='notify')toggleNotify();else if(a==='backup')backup();else if(a==='restore')$('#backupInput').click();else if(a==='changePin')changePin();else if(a==='lock')lock()}
async function saveExpense(d,id){let x={id:id||uid(),title:d.title||'Gider',amount:+d.amount||0,category:d.category,date:d.date||iso(),dueDate:d.dueDate||d.date||iso(),day:+d.day||1,recurring:d.recurring==='true',paid:d.paid==='true'};if(modal.attachment)x.attachment=modal.attachment;if(id){let i=state.expenses.findIndex(z=>z.id===id);x.attachment=x.attachment||state.expenses[i].attachment;state.expenses[i]={...state.expenses[i],...x}}else state.expenses.push(x);await save();close();toast('Gider kaydedildi')}
async function saveIncome(d,id){let x={id:id||uid(),title:d.title||'Gelir',amount:+d.amount||0,date:d.date||iso(),day:+d.day||20,recurring:d.recurring==='true'};if(id){let i=state.incomes.findIndex(z=>z.id===id);state.incomes[i]={...state.incomes[i],...x}}else state.incomes.push(x);await save();close();toast('Gelir kaydedildi')}
async function saveCard(d,id){let x={id:id||uid(),bank:d.bank||'Banka',name:d.name||'Kart',last4:(d.last4||'0000').replace(/\D/g,'').slice(-4).padStart(4,'0'),limit:+d.limit||0,balance:+d.balance||0,statementDay:+d.statementDay||10,dueDay:+d.dueDay||20,style:d.style||'goldish',network:'VISA',transactions:[]};if(id){let i=state.cards.findIndex(z=>z.id===id);x.transactions=state.cards[i].transactions||[];state.cards[i]={...state.cards[i],...x}}else state.cards.push(x);await save();close();toast('Kart kaydedildi')}
async function saveSpend(d,cardId){let c=state.cards.find(x=>x.id===cardId),t={id:uid(),amount:+d.amount||0,category:d.category,title:d.title||d.category,date:d.date||iso(),attachment:modal.attachment||''};c.transactions.push(t);c.balance=+c.balance+t.amount;state.expenses.push({id:uid(),cardTxId:t.id,title:t.title,amount:t.amount,category:t.category,date:t.date,dueDate:t.date,paid:true,recurring:false,attachment:t.attachment});await save();close();toast('Kart harcaması eklendi')}

async function updateTx(d,cardId,txId){let c=state.cards.find(x=>x.id===cardId),i=c.transactions.findIndex(x=>x.id===txId),old=c.transactions[i],neu={...old,amount:+d.amount||0,category:d.category,title:d.title||d.category,date:d.date};c.balance=+c.balance-+old.amount+neu.amount;c.transactions[i]=neu;let ex=state.expenses.find(x=>x.cardTxId===txId);if(ex)Object.assign(ex,{amount:neu.amount,category:neu.category,title:neu.title,date:neu.date,dueDate:neu.date});await save();close();toast('Kart harcaması güncellendi')}
async function deleteTx(cardId,txId){let c=state.cards.find(x=>x.id===cardId),t=c.transactions.find(x=>x.id===txId);if(!t)return;c.transactions=c.transactions.filter(x=>x.id!==txId);c.balance=Math.max(0,+c.balance-+t.amount);state.expenses=state.expenses.filter(x=>x.cardTxId!==txId);await save();close();toast('Kart harcaması silindi')}
async function toggleNotify(){if(!('Notification'in window)){toast('Tarayıcı bildirim desteklemiyor');return}if(Notification.permission!=='granted'&&(await Notification.requestPermission())!=='granted'){toast('Bildirim izni verilmedi');return}state.settings.notifications=!state.settings.notifications;await save();render();maybeNotify()}
async function maybeNotify(){if(!state?.settings.notifications||Notification.permission!=='granted')return;for(const x of dues()){let k='HN_'+iso()+'_'+x.type+x.id;if(localStorage.getItem(k))continue;new Notification('HANE · Ödeme Hatırlatması',{body:`${x.title}: ${money(x.amount)} · ${x.days<=0?'ödeme zamanı':x.days+' gün kaldı'}`,icon:'./icons/icon-192.png'});localStorage.setItem(k,'1')}}
async function backup(){let payload={format:'HANE-BACKUP',version:1,meta:meta(),box:JSON.parse(localStorage.getItem(APP)),exportedAt:new Date().toISOString()},u=URL.createObjectURL(new Blob([JSON.stringify(payload)],{type:'application/octet-stream'})),a=document.createElement('a');a.href=u;a.download='HANE-'+iso()+'.hane';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);toast('Şifreli yedek oluşturuldu')}
async function restoreFile(f){try{let b=JSON.parse(await f.text()),p=prompt('Yedeğin PIN’ini girin:');if(!p)return;let k=await derive(p,ub64(b.meta.salt)),st=await decrypt(b.box,k);state=st;await save();render();toast('Yedek geri yüklendi')}catch{alert('Yedek açılamadı. PIN yanlış veya dosya bozuk.')}}
async function changePin(){let old=prompt('Mevcut PIN:');if(!old||!(await unlock(old))){alert('Mevcut PIN yanlış.');return}let n=prompt('Yeni 4 haneli PIN:');if(!/^\d{4}$/.test(n||'')){alert('PIN tam 4 rakam olmalı.');return}let st=state,salt=crypto.getRandomValues(new Uint8Array(16));key=await derive(n,salt);localStorage.setItem(META,JSON.stringify({salt:b64(salt),publicName:st.profile.name,publicPhoto:st.profile.photo||''}));state=st;await save();toast('PIN değiştirildi')}
function draw(){let c=$('#chart');if(!c)return;let ctx=c.getContext('2d'),r=c.getBoundingClientRect(),dpr=devicePixelRatio||1;c.width=r.width*dpr;c.height=230*dpr;ctx.scale(dpr,dpr);let w=r.width,h=230,p=25;ctx.clearRect(0,0,w,h);ctx.strokeStyle='#1d3446';for(let y=20;y<h-25;y+=40){ctx.beginPath();ctx.moveTo(p,y);ctx.lineTo(w-8,y);ctx.stroke()}let inc=[],exp=[],labels=[];const add=(arr,i,v)=>arr[i]=(arr[i]||0)+Number(v);if(reportPeriod==='year'){let Y=+state.selectedMonth.slice(0,4);inc=Array(12).fill(0);exp=Array(12).fill(0);labels=['O','Ş','M','N','M','H','T','A','E','E','K','A'];state.incomes.filter(x=>x.date.startsWith(String(Y))).forEach(x=>add(inc,+x.date.slice(5,7)-1,x.amount));state.expenses.filter(x=>x.date.startsWith(String(Y))).forEach(x=>add(exp,+x.date.slice(5,7)-1,x.amount))}else if(reportPeriod==='week'){inc=Array(7).fill(0);exp=Array(7).fill(0);labels=['1','2','3','4','5','6','7'];state.incomes.filter(x=>x.date.startsWith(state.selectedMonth)&&+x.date.slice(8)<=7).forEach(x=>add(inc,+x.date.slice(8)-1,x.amount));state.expenses.filter(x=>x.date.startsWith(state.selectedMonth)&&+x.date.slice(8)<=7).forEach(x=>add(exp,+x.date.slice(8)-1,x.amount))}else if(reportPeriod==='day'){let target=state.selectedMonth===ym()?iso():state.selectedMonth+'-01';inc=[state.incomes.filter(x=>x.date===target).reduce((s,x)=>s+Number(x.amount),0)];exp=[state.expenses.filter(x=>x.date===target).reduce((s,x)=>s+Number(x.amount),0)];labels=[target.slice(8)]}else{let [Y,M]=state.selectedMonth.split('-').map(Number),days=new Date(Y,M,0).getDate(),bucket=Math.ceil(days/6);inc=Array(6).fill(0);exp=Array(6).fill(0);labels=Array.from({length:6},(_,i)=>String(i*bucket+1));state.incomes.filter(x=>x.date.startsWith(state.selectedMonth)).forEach(x=>add(inc,Math.min(5,Math.floor((+x.date.slice(8)-1)/bucket)),x.amount));state.expenses.filter(x=>x.date.startsWith(state.selectedMonth)).forEach(x=>add(exp,Math.min(5,Math.floor((+x.date.slice(8)-1)/bucket)),x.amount))}let max=Math.max(1,...inc,...exp),n=inc.length,bw=(w-p-15)/Math.max(1,n);for(let i=0;i<n;i++){let x=p+i*bw+5,hi=inc[i]/max*(h-58),he=exp[i]/max*(h-58);ctx.fillStyle='#2d8cff';ctx.fillRect(x,h-30-hi,Math.max(5,bw*.28),hi);ctx.fillStyle='#ff525c';ctx.fillRect(x+bw*.32,h-30-he,Math.max(5,bw*.28),he);ctx.fillStyle='#8297a8';ctx.font='9px sans-serif';ctx.fillText(labels[i]||'',x,h-11)}}
function readImg(f,cb,kind='receipt'){
  const r=new FileReader();
  r.onload=()=>{
    const img=new Image();
    img.onload=()=>{
      const max=kind==='profile'?320:1280;
      let w=img.width,h=img.height;
      if(Math.max(w,h)>max){
        const s=max/Math.max(w,h);w=Math.round(w*s);h=Math.round(h*s);
      }
      const c=document.createElement('canvas');c.width=w;c.height=h;
      c.getContext('2d').drawImage(img,0,0,w,h);
      cb(c.toDataURL('image/jpeg',kind==='profile'?.78:.72));
    };
    img.onerror=()=>cb(r.result);
    img.src=r.result;
  };
  r.readAsDataURL(f);
}
function lock(){key=null;state=null;pinBuf='';renderLock()}function schedule(){clearTimeout(lockTimer);if(state)lockTimer=setTimeout(lock,(+state.settings.lockMinutes||15)*60000)};['click','touchstart','keydown'].forEach(ev=>document.addEventListener(ev,schedule,{passive:true}));document.addEventListener('visibilitychange',()=>{if(document.hidden)hiddenAt=Date.now();else if(state&&hiddenAt&&Date.now()-hiddenAt>(+state.settings.lockMinutes||15)*60000)lock()})
function renderSetup(){$('#app').innerHTML=`<div class="setup"><div class="house-logo">⌂</div><h1>HANE</h1><p class="intro">Premium ev bütçen. Verilerin cihazında şifreli saklanır.</p><form class="form" id="setupForm"><div class="photo-pick"><div class="avatar" id="setupAvatar">H</div><button class="btn" type="button" id="setupPhoto">Profil Resmi Seç</button></div>${inp('name','İsim','Mehmet')}${inp('pin','4 Haneli PIN','','password','inputmode="numeric" maxlength="4"')}${inp('pin2','PIN Tekrar','','password','inputmode="numeric" maxlength="4"')}<button class="btn goldbtn">HANE’yi Kur</button></form><div class="notice" style="margin-top:14px">PIN’ini unutursan şifreli veriler açılamaz.</div></div>`;setupPhotoData='';$('#setupPhoto').onclick=()=>$('#profileInput').click();$('#setupForm').onsubmit=async e=>{
  e.preventDefault();
  let d=formData(e.target);
  if(!/^\d{4}$/.test(d.pin)||d.pin!==d.pin2){alert('PIN tam 4 rakam olmalı ve iki alan aynı olmalı.');return}
  const btn=e.target.querySelector('button[type="submit"]'); if(btn){btn.disabled=true;btn.textContent='Kuruluyor…'}
  try{
    let st=defaultState();st.profile.name=d.name||'Mehmet';st.profile.photo=setupPhotoData;
    await setup(d.pin,st);
    render();schedule();toast('HANE hazır');
  }catch(err){
    alert(err.message||'Kurulum tamamlanamadı.');
    if(btn){btn.disabled=false;btn.textContent='HANE’yi Kur'}
  }
}}
function renderLock(){if(!meta()){renderSetup();return}let mm=meta();$('#app').innerHTML=`<div class="lock"><div class="house-logo">⌂</div><h1>HANE</h1><p>Daha huzurlu yarınlar senin elinde</p><div class="profile-big">${mm.publicPhoto?`<img src="${mm.publicPhoto}" style="width:100%;height:100%;object-fit:cover">`:esc((mm.publicName||'H')[0])}</div><h2>${esc(mm.publicName||'HANE')}</h2><div class="pin-dots">${[0,1,2,3].map(i=>`<i data-dot="${i}"></i>`).join('')}</div><div class="keypad">${[1,2,3,4,5,6,7,8,9].map(n=>`<button data-key="${n}">${n}</button>`).join('')}<button class="zero" data-key="0">0</button><button data-key="del">⌫</button></div><small style="color:#91a4b3;margin-top:20px">Güvenli ve sadece senin</small></div>`;$$('[data-key]').forEach(b=>b.onclick=()=>pinKey(b.dataset.key))}
async function pinKey(k){
  if(k==='del'){pinBuf=pinBuf.slice(0,-1)}
  else if(pinBuf.length<4){pinBuf+=k}
  $$('[data-dot]').forEach((d,i)=>d.classList.toggle('on',i<pinBuf.length));
  if(pinBuf.length===4){
    const ok=await unlock(pinBuf);
    if(ok){
      try{render();schedule();maybeNotify();return}
      catch(err){console.error(err);alert('Ana ekran açılırken hata: '+(err.message||err));return}
    }
    pinBuf='';$$('[data-dot]').forEach(d=>d.classList.remove('on'));
    const hasData=!!localStorage.getItem(APP);
    toast(hasData?'PIN yanlış':'Kurulum verisi eksik · Uygulamayı sıfırlayın');
  }
}
$('#cameraInput').onchange=e=>{let f=e.target.files[0];if(f)readImg(f,x=>{if(modal){modal.attachment=x;render();toast('Fiş fotoğrafı eklendi')}})};$('#galleryInput').onchange=e=>{let f=e.target.files[0];if(f)readImg(f,x=>{if(modal){modal.attachment=x;render();toast('Fotoğraf eklendi')}})};$('#profileInput').onchange=e=>{let f=e.target.files[0];if(!f)return;readImg(f,async x=>{if(state){state.profile.photo=x;let mm=meta();mm.publicPhoto=x;localStorage.setItem(META,JSON.stringify(mm));try{await save();render();toast('Profil resmi güncellendi')}catch(err){alert(err.message)}}else{setupPhotoData=x;let a=$('#setupAvatar');if(a)a.innerHTML=`<img src="${x}" style="width:100%;height:100%;object-fit:cover">`}},'profile')};$('#backupInput').onchange=e=>{let f=e.target.files[0];if(f)restoreFile(f)};
async function boot(){
 try{
   if('serviceWorker' in navigator){
     const regs=await navigator.serviceWorker.getRegistrations();
     await Promise.all(regs.map(r=>r.unregister()));
   }
   if(meta()&&!localStorage.getItem(APP)){
     localStorage.removeItem(META);
   }
   renderLock();
 }catch(err){
   console.error(err);
   document.getElementById('app').innerHTML='<div class=\"setup\"><h1>HANE</h1><div class=\"notice\">Uygulama başlatılamadı. Sayfayı yenileyin. Devam ederse Site verilerini temizleyin.</div><button class=\"btn goldbtn\" id=\"resetApp\">Uygulamayı Sıfırla</button></div>';
   document.getElementById('resetApp')?.addEventListener('click',()=>{localStorage.removeItem(APP);localStorage.removeItem(META);location.reload()});
 }
}
boot();
